In [1]:
import pandas as pd
import numpy as np



va_activity_loc_assign = pd.read_csv('va_activity_location_assignment.csv.gz', compression='gzip').iloc[:,1:]
va_activity_locations = pd.read_csv('va_activity_locations.csv.gz', compression='gzip').iloc[:,1:]
va_disease_outcome_target = pd.read_csv('va_disease_outcome_target.csv.gz', compression='gzip').iloc[:,1:]
va_disease_outcome_training = pd.read_csv('va_disease_outcome_training.csv.gz', compression='gzip')
va_household = pd.read_csv('va_household.csv.gz', compression = 'gzip').iloc[:,1:]
va_person = pd.read_csv('va_person.csv.gz', compression='gzip')
va_population_network = pd.read_csv('va_population_network.csv.gz', compression='gzip')
va_residence_locations = pd.read_csv('va_residence_locations.csv.gz', compression='gzip').iloc[:,1:]
# va_residence_locations.head()

In [2]:
from graphstats import GraphStats

In [3]:
test = GraphStats(va_activity_loc_assign, va_activity_locations, va_disease_outcome_target, va_disease_outcome_training, va_household, va_person, va_population_network, va_residence_locations)  

#print(va_activity_loc_assign.head(20))
print(test.get_location_durations(4543749))
#test.get_raw_time_with_infected_day(4543889,21)
#test.get_raw_time_with_infected_week(4543889, 50)

{1001002120: 69479, 86307: 13020, 3474: 840}


In [4]:
print(va_disease_outcome_training.head())
print(va_disease_outcome_target.head())

   Unnamed: 0  day      pid state
0     4543749    0  4543749     S
1     4543750    0  4543750     S
2     4543751    0  4543751     S
3     4543752    0  4543752     S
4     4543753    0  4543753     S
       pid  infected
0  4543749         0
1  4543750         0
2  4543751         0
3  4543752         0
4  4543753         0


In [5]:
from preprocess import PreProcessor
import run



In [6]:
run.run(va_activity_loc_assign, va_activity_locations, va_disease_outcome_target, va_disease_outcome_training, va_household, va_person, va_population_network, va_residence_locations)

[[   37     2     0 ...     0 69479 13860]
 [    7     1     0 ...     0 53999 28800]
 [    5     2     0 ...     0 62219 21300]
 ...
 [   54     2     0 ...     0     0 86399]
 [   56     1     0 ...     0     0 86399]
 [   35     2     0 ...     0 67199 12600]]
[[   37     2     0 ...     0 69479 13860]
 [    7     1     0 ...     0 53999 28800]
 [    5     2     0 ...     0 62219 21300]
 ...
 [   54     2     0 ...     0     0 86399]
 [   56     1     0 ...     0     0 86399]
 [   35     2     0 ...     0 67199 12600]]
[4543749 4543750 4543751 ... 4550889 4550890 4550891]
[ 6  6  6 ... 56 56 56]
[[   37     2     0 ...     0 69479 13860]
 [    7     1     0 ...     0 53999 28800]
 [    5     2     0 ...     0 62219 21300]
 ...
 [   54     2     0 ...     0     0 86399]
 [   56     1     0 ...     0     0 86399]
 [   35     2     0 ...     0 67199 12600]]
BAP: 0.000351365510141477
Epoch [1/100], Loss: 1.3371
Confusion matrix:
 [[359355   4810]
 [   128      0]]
BAP: 0.000351365510141