In [1]:
import pandas as pd
import numpy as np
import pickle


va_activity_loc_assign = pd.read_csv('va_activity_location_assignment.csv.gz', compression='gzip').iloc[:,1:]
va_activity_locations = pd.read_csv('va_activity_locations.csv.gz', compression='gzip').iloc[:,1:]
va_disease_outcome_target = pd.read_csv('va_disease_outcome_target.csv.gz', compression='gzip').iloc[:,1:]
va_disease_outcome_training = pd.read_csv('va_disease_outcome_training.csv.gz', compression='gzip')
va_household = pd.read_csv('va_household.csv.gz', compression = 'gzip').iloc[:,1:]
va_person = pd.read_csv('va_person.csv.gz', compression='gzip')
va_population_network = pd.read_csv('va_population_network.csv.gz', compression='gzip')
va_residence_locations = pd.read_csv('va_residence_locations.csv.gz', compression='gzip').iloc[:,1:]
# va_residence_locations.head()

In [2]:
from graphstats import GraphStats

In [3]:
# test = GraphStats(va_activity_loc_assign, va_activity_locations, va_disease_outcome_target, va_disease_outcome_training, va_household, va_person, va_population_network, va_residence_locations)  
# dataset = test.get_dataset()

# with open("new_dataset.pickle", "wb") as f:
#     pickle.dump(dataset, f)
#print(va_activity_loc_assign.head(20))
#print(test.get_location_durations(4543749))
#test.get_raw_time_with_infected_day(4543889,21)
#test.get_raw_time_with_infected_week(4543889, 50)


In [4]:
print(va_disease_outcome_training.head())
print(va_disease_outcome_target.head())

   Unnamed: 0  day      pid state
0     4543749    0  4543749     S
1     4543750    0  4543750     S
2     4543751    0  4543751     S
3     4543752    0  4543752     S
4     4543753    0  4543753     S
       pid  infected
0  4543749         0
1  4543750         0
2  4543751         0
3  4543752         0
4  4543753         0


In [5]:
from preprocess import PreProcessor
import run
# data = []
# with open('new_dataset.pickle', 'rb') as f:
#     data = pickle.load(f)
# data


In [6]:
model = run.run(va_activity_loc_assign, va_activity_locations, va_disease_outcome_target, va_disease_outcome_training, va_household, va_person, va_population_network, va_residence_locations)

48
BAP: 0.13145454227924347
Epoch [1/100], Loss: 41.8815
Confusion matrix:
 [[191 109]
 [ 33  15]]
BAP: 0.14418426156044006
Epoch [2/100], Loss: 35.9191
Confusion matrix:
 [[215  85]
 [ 32  16]]
BAP: 0.1260097175836563
Epoch [3/100], Loss: 42.0281
Confusion matrix:
 [[204  96]
 [ 40   8]]
BAP: 0.13616004586219788
Epoch [4/100], Loss: 32.4747
Confusion matrix:
 [[238  62]
 [ 39   9]]
BAP: 0.1554964780807495
Epoch [5/100], Loss: 33.3586
Confusion matrix:
 [[223  77]
 [ 32  16]]
BAP: 0.13354341685771942
Epoch [6/100], Loss: 34.7412
Confusion matrix:
 [[224  76]
 [ 37  11]]
BAP: 0.1332414299249649
Epoch [7/100], Loss: 33.7227
Confusion matrix:
 [[235  65]
 [ 39   9]]
BAP: 0.16386514902114868
Epoch [8/100], Loss: 29.1861
Confusion matrix:
 [[240  60]
 [ 32  16]]
BAP: 0.1451149433851242
Epoch [9/100], Loss: 29.1270
Confusion matrix:
 [[251  49]
 [ 38  10]]
BAP: 0.13140569627285004
Epoch [10/100], Loss: 33.0544
Confusion matrix:
 [[242  58]
 [ 41   7]]
BAP: 0.13987968862056732
Epoch [11/100],