In [47]:
import pandas as pd
import numpy as np



va_activity_loc_assign = pd.read_csv('va_activity_location_assignment.csv.gz', compression='gzip').iloc[:,1:]
va_activity_locations = pd.read_csv('va_activity_locations.csv.gz', compression='gzip').iloc[:,1:]
va_disease_outcome_target = pd.read_csv('va_disease_outcome_target.csv.gz', compression='gzip').iloc[:,1:]
va_disease_outcome_training = pd.read_csv('va_disease_outcome_training.csv.gz', compression='gzip')
va_household = pd.read_csv('va_household.csv.gz', compression = 'gzip').iloc[:,1:]
va_person = pd.read_csv('va_person.csv.gz', compression='gzip')
va_population_network = pd.read_csv('va_population_network.csv.gz', compression='gzip')
va_residence_locations = pd.read_csv('va_residence_locations.csv.gz', compression='gzip').iloc[:,1:]
# va_residence_locations.head()
infected_pids = set(va_disease_outcome_training.query('state == "I"')['pid'].unique())


In [58]:
from graphstats import GraphStats
test = GraphStats(va_activity_loc_assign, va_activity_locations, va_disease_outcome_target, va_disease_outcome_training, va_household, va_person, va_population_network, va_residence_locations)  
infected_pids

array([4549700, 4545534, 4546979, 4550192, 4546013, 4550551, 4545070,
       4546077, 4549153, 4544155, 4544534, 4548849, 4548019, 4548615,
       4548301, 4549126, 4545834, 4548021], dtype=int64)

In [52]:
pid = 4545426 
interactions = va_population_network.query('pid1 == @pid or pid2 == @pid')
interactions

Unnamed: 0     pid1     pid2     lid  start_time  duration  activity1  \
904         829090  4545426  2315681    3346       50940       960          3   
905         829091  4545426  2255497    3346       50940      1860          3   
906         829092  4545426  2284321    3346       50940      1260          3   
907         829118  2258002  4545426    3346       51900       300          3   
908         829151  2264206  4545426    3346       52500       600          3   
909         829191  2275407  4545426    3346       54600       240          3   
2085       1853106  4545426  2312440   14842       58380       300          3   
2086       1853107  4545426  2308306   14842       58380       300          3   
2087       1853108  4545426  2256076   14842       58380       300          3   
4302       3968146  4545426  1084039   29147       58800      1800          3   
4303       3968147  4545426  2276154   29147       58800      3540          3   
4306       3968155  6267694  4545426   29147       59400       900          3   
4307       3968157  2282244  4545426   29147       59400       300          3   
4312       3968188  3936481  4545426   29147       61200      1140          3   
4313       3968197  2312089  4545426   29147       61200      1140          3   
10103      7148619  4545426  4546783   56811       55800      1500          3   
10112      7148628  4550598  4545426   56811       55800      1200          3   
10129      7148645  4546979  4545426   56811       56280       540          3   
10158      7148674  4550391  4545426   56811       56880       420          3   
10172      7148688  4548807  4545426   56811       57180       120          3   
50393     54205054  4545426  4804235   83748       33960      4980          4   
50394     54205055  4545426  4101585   83748       33960      4980          4   
50395     54205056  4545426  2283316   83748       33960      4980          4   
50396     54205057  4545426  4161157   83748       33960      4980          4   
50397     54205058  4545426  2317716   83748       33960      4980          4   
50398     54205059  4545426  2026626   83748       33960      4980          4   
50399     54205060  4545426  2276870   83748       33960      4980          4   
50400     54205061  4545426  1134705   83748       33960      4980          4   
50401     54205062  4545426  2305049   83748       33960      4980          4   
50402     54205063  4545426  2313841   83748       33960      4980          4   
50403     54205064  4545426  2256339   83748       33960      4980          4   
50404     54205065  4545426  2265531   83748       33960      4980          4   
50405     54205066  4545426  2301733   83748       33960      4980          4   
50484     54205789  2318834  4545426   83748       36090      2850          4   
50508     54206133  2300104  4545426   83748       37200      1740          2   
50522     54206553  2273428  4545426   83748       38220       720          4   
69309     69287506  4545426  2255721   88741       48300       720          4   
173753   129922256  4545426  1120172  124934       46200       540          4   
173754   129922257  4545426  1130059  124934       46200       540          4   
173755   129922258  4545426  2281349  124934       46200       540          4   
173756   129922259  4545426  5106589  124934       46200       540          4   
173757   129922260  4545426  5093491  124934       46200       540          4   
173758   129922261  4545426  2316716  124934       46200       540          4   
173759   129922262  4545426  4358040  124934       46200       540          4   
173760   129922263  4545426  2318522  124934       46200       540          4   
173761   129922264  4545426  2260370  124934       46200       540          4   
173762   129922265  4545426  1115380  124934       46200       540          4   
173763   129922266  4545426  2310630  124934       46200       540          4   
173764   129922267  4545426  2309080  1

In [59]:
pid1 = interactions['pid1'].to_numpy()
pid2 = interactions['pid2'].to_numpy()
pids = np.concatenate((pid1, pid2))
pids = np.unique(pids[pids!=pid])
print(pids)

num_contact_with_infected = sum(1 for pid in pids if pid in infected_pids)
num_contact = pids.size
# va_disease_outcome_training.query('pid in @pids and state == "I"')


[1084039 1115380 1120172 1130059 1134705 2026626 2255497 2255721 2255957
 2256076 2256339 2257292 2258002 2260370 2264206 2265531 2273428 2275407
 2276154 2276870 2279349 2281349 2282244 2283316 2284321 2300104 2301422
 2301733 2305049 2308306 2309080 2310630 2312089 2312440 2313841 2315681
 2316716 2317716 2318522 2318834 3936481 4101585 4115951 4161157 4358040
 4546783 4546979 4548807 4550391 4550598 4804235 5093491 5106589 6267694]


54

In [57]:
infected_pids = va_disease_outcome_training.query('state == "I"')['pid'].unique()
infected_pids

array([4549700, 4545534, 4546979, 4550192, 4546013, 4550551, 4545070,
       4546077, 4549153, 4544155, 4544534, 4548849, 4548019, 4548615,
       4548301, 4549126, 4545834, 4548021], dtype=int64)

In [51]:
va_population_network.query('pid1 == 4546979 or pid2 == 4546979')

Unnamed: 0     pid1     pid2         lid  start_time  duration  \
10129      7148645  4546979  4545426       56811       56280       540   
10130      7148646  4546979  4545431       56811       56280       540   
10131      7148647  4546979  4547567       56811       56280       540   
10132      7148648  4546979  4545676       56811       56280       540   
10133      7148649  4546979  4548178       56811       56280       540   
10472      7148990  4546979  4544896       56811       73740      1260   
10473      7148991  4546979  4544164       56811       73740        60   
10475      7148993  4550193  4546979       56811       74340      2040   
47370     52932195  4546979  4546642       84149       51660      4380   
47371     52932196  4546979  4544749       84149       51660      4380   
47372     52932197  4546979  4545176       84149       51660      4380   
47373     52932198  4546979  4547598       84149       51660      4380   
47374     52932199  4546979  4549282       84149       51660      4380   
47375     52932200  4546979  5194566       84149       51660      4380   
47376     52932201  4546979  4546031       84149       51660      4380   
47379     52932204  4545102  4546979       84149       52200      3600   
47422     52932251  4548272  4546979       84149       54300      1740   
47426     52932255  4550787  4546979       84149       54330       300   
47432     52932261  1113923  4546979       84149       54840      1200   
47442     52932271  4550096  4546979       84149       54900      1140   
206876   159894514  4546979  4546983  1000147007           0     14400   
206877   159894515  4546979  4546978  1000147007           0     14400   
206878   159894516  4546979  4546980  1000147007           0     14400   
206879   159894517  4546979  4546982  1000147007           0     14400   
206880   159894518  4546979  4546981  1000147007           0     14400   
206881   159894519  4546980  4546979  1000147007       14400     14400   
206882   159894520  4546981  4546979  1000147007       14400     24960   
206884   159894522  4546982  4546979  1000147007       14400      9480   
206887   159894525  4546983  4546979  1000147007       14400     15300   
206891   159894529  4546978  4546979  1000147007       21540     29520   
206897   159894535  4546979  4546981  1000147007       57540        60   
206898   159894536  4546979  4546978  1000147007       57540      5700   
206899   159894537  4546983  4546979  1000147007       58800      5280   
206902   159894540  4546980  4546979  1000147007       60000      4080   
206906   159894544  4546979  4546983  1000147007       65640      7380   
206907   159894545  4546979  4546978  1000147007       65640      7380   
206908   159894546  4546979  4546980  1000147007       65640      7380   
206912   159894550  4546982  4546979  1000147007       66600      6420   
206916   159894554  4546981  4546979  1000147007       68280      4740   
206922   159894560  4546979  4546983  1000147007       77160      9239   
206923   159894561  4546979  4546978  1000147007       77160      9239   
206924   159894562  4546979  4546980  1000147007       77160      9239   
206925   159894563  4546979  4546982  1000147007       77160      9239   
206926   159894564  4546979  4546981  1000147007       77160      9239   

        activity1  activity2  
10129           3          3  
10130           3          3  
10131           3          3  
10132           3          3  
10133           3          3  
10472           3          3  
10473           3          3  
10475           2          3  
47370           4          4  
47371           4          2  
47372           4          2  
47373           4          2  
47374           4          2  
47375           4          2  
47376           4          2  
47379           4          4  
47422           2          4  
47426           4          4  
47432           2          4  
47442           4          4  
206876          1         

In [29]:
infected_pids = va_disease_outcome_training.query('state == "I"')['pid']
infected_pids

113096    4549700
120239    4549700
127382    4549700
134525    4549700
144645    4545534
146090    4546979
151788    4545534
153233    4546979
156446    4550192
158931    4545534
160376    4546979
166074    4545534
173217    4545534
202268    4546013
209411    4546013
216554    4546013
221092    4550551
223697    4546013
228235    4550551
230840    4546013
235378    4550551
237983    4546013
245126    4546013
258469    4545070
265612    4545070
272755    4545070
279898    4545070
280905    4546077
288048    4546077
312553    4549153
328984    4544155
329363    4544534
336506    4544534
340821    4548849
347134    4548019
354277    4548019
361420    4548019
368563    4548019
369159    4548615
375706    4548019
376302    4548615
382849    4548019
383445    4548615
390274    4548301
398242    4549126
402093    4545834
404280    4548021
405385    4549126
Name: pid, dtype: int64

In [26]:
va_disease_outcome_training.query('state == "I"')


Unnamed: 0  day      pid state
113096   119870585   15  4549700     I
120239   127558644   16  4549700     I
127382   135246703   17  4549700     I
134525   142934762   18  4549700     I
144645   158306714   20  4545534     I
146090   158308159   20  4546979     I
151788   165994773   21  4545534     I
153233   165996218   21  4546979     I
156446   165999431   21  4550192     I
158931   173682832   22  4545534     I
160376   173684277   22  4546979     I
166074   181370891   23  4545534     I
173217   189058950   24  4545534     I
202268   219811665   28  4546013     I
209411   227499724   29  4546013     I
216554   235187783   30  4546013     I
221092   235192321   30  4550551     I
223697   242875842   31  4546013     I
228235   242880380   31  4550551     I
230840   250563901   32  4546013     I
235378   250568439   32  4550551     I
237983   258251960   33  4546013     I
245126   265940019   34  4546013     I
258469   281315194   36  4545070     I
265612   289003253   37  4545070     I
272755   296691312   38  4545070     I
279898   304379371   39  4545070     I
280905   304380378   39  4546077     I
288048   312068437   40  4546077     I
312553   335135690   43  4549153     I
328984   358194869   46  4544155     I
329363   358195248   46  4544534     I
336506   365883307   47  4544534     I
340821   365887622   47  4548849     I
347134   373574851   48  4548019     I
354277   381262910   49  4548019     I
361420   388950969   50  4548019     I
368563   396639028   51  4548019     I
369159   396639624   51  4548615     I
375706   404327087   52  4548019     I
376302   404327683   52  4548615     I
382849   412015146   53  4548019     I
383445   412015742   53  4548615     I
390274   419703487   54  4548301     I
398242   427392371   55  4549126     I
402093   435077138   56  4545834     I
404280   435079325   56  4548021     I
405385   435080430   56  4549126     I

In [6]:
# get number of infected people a person come into contact with
def get_num_contact_with_infected(pid):
    
    va_disease_outcome_training.query('state == "I"')

# get number of people a person come into contact with


Unnamed: 0  day      pid state
113096   119870585   15  4549700     I
120239   127558644   16  4549700     I
127382   135246703   17  4549700     I
134525   142934762   18  4549700     I
144645   158306714   20  4545534     I
146090   158308159   20  4546979     I
151788   165994773   21  4545534     I
153233   165996218   21  4546979     I
156446   165999431   21  4550192     I
158931   173682832   22  4545534     I
160376   173684277   22  4546979     I
166074   181370891   23  4545534     I
173217   189058950   24  4545534     I
202268   219811665   28  4546013     I
209411   227499724   29  4546013     I
216554   235187783   30  4546013     I
221092   235192321   30  4550551     I
223697   242875842   31  4546013     I
228235   242880380   31  4550551     I
230840   250563901   32  4546013     I
235378   250568439   32  4550551     I
237983   258251960   33  4546013     I
245126   265940019   34  4546013     I
258469   281315194   36  4545070     I
265612   289003253   37  4545070     I
272755   296691312   38  4545070     I
279898   304379371   39  4545070     I
280905   304380378   39  4546077     I
288048   312068437   40  4546077     I
312553   335135690   43  4549153     I
328984   358194869   46  4544155     I
329363   358195248   46  4544534     I
336506   365883307   47  4544534     I
340821   365887622   47  4548849     I
347134   373574851   48  4548019     I
354277   381262910   49  4548019     I
361420   388950969   50  4548019     I
368563   396639028   51  4548019     I
369159   396639624   51  4548615     I
375706   404327087   52  4548019     I
376302   404327683   52  4548615     I
382849   412015146   53  4548019     I
383445   412015742   53  4548615     I
390274   419703487   54  4548301     I
398242   427392371   55  4549126     I
402093   435077138   56  4545834     I
404280   435079325   56  4548021     I
405385   435080430   56  4549126     I

In [12]:
test.va_person.query('pid == 4543749')['hid'][0]

1781818

In [32]:
test.va_person.query('hid == 1781818')['pid'].to_numpy()


array([4543749, 4543750, 4543751, 4543752], dtype=int64)

In [6]:

test.get_household_size(4543749)


4

In [16]:
test.va_household.query('hid == 1781818')

hid        rlid  admin1  admin2  hh_size
0  1781818  1001002120      51     157        4

In [62]:
print(va_disease_outcome_training.head())
print(va_disease_outcome_target.head())

   Unnamed: 0  day      pid state
0     4543749    0  4543749     S
1     4543750    0  4543750     S
2     4543751    0  4543751     S
3     4543752    0  4543752     S
4     4543753    0  4543753     S
       pid  infected
0  4543749         0
1  4543750         0
2  4543751         0
3  4543752         0
4  4543753         0


In [3]:
import pickle
with open('dataset_day56.pkl', 'rb') as f:
    data = pickle.load(f)
data

[[4543749,
  56,
  37,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  69479,
  13020,
  840,
  0,
  0,
  0,
  69479,
  13860],
 [4543750,
  56,
  7,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  53999,
  0,
  0,
  0,
  28800,
  0,
  53999,
  28800],
 [4543751,
  56,
  5,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  62219,
  0,
  1500,
  300,
  19500,
  0,
  62219,
  21300],
 [4543752,
  56,
  36,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  52259,
  29160,
  1500,
  0,
  0,
  0,
  52259,
  30660],
 [4543753,
  56,
  41,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  45659,
  37380,
  0,
  0,
  0,
  0,
  45659,
  37380],
 [4543754,
  56,
  39,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  43679,
  0,
  0,
  40680,
  0,
  0,
  43679,
  40680],
 [4543755,
  56,
  9,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  52499,
  0,
  0,
  6600,
  24300,
  0,
  52499,
  30900],
 [4543756,
  56,
  7,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  57599,
  0,
  0,
  0,
  25680,
  0,
  57599,
  25680],
 [4543757,
  56,
  51,
  1,
  0

In [65]:

# print(va_activity_loc_assign.head(20))
# print(test.get_location_durations(4543749))
# test.get_raw_time_with_infected_day(4543889,21)
# test.get_raw_time_with_infected_week(4543889, 50)

# for pid in test.va_person["pid"]:
#     get_age_sex
pid_list = test.va_person["pid"].unique()
for day in range(6, 56):
    for pid in pid_list:
        print(pid)
        
        try:
            household_members = test.household_members(pid) # get household members for this person pid, this is a list of pids [pid1, pid2, pid3, etc...]
        except:
            pass
        print(household_members)
        age, sex = test.get_age_sex(pid) # get age and sex
        infected_week_time = test.get_raw_time_with_infected_week(pid, day=day)
        print(infected_week_time)
        # test.get_raw_time_with_infected_week(pid=4543749, day=1)
        # [pid, day, ]
        # print(day)
# va_disease_outcome_training


4543749
[4543749 4543750 4543751 4543752]
   Unnamed: 0      hid      pid  person_number  age  sex
0     4543749  1781818  4543749              1   37    2
1     4543750  1781818  4543750              2    7    1
2     4543751  1781818  4543751              3    5    2
3     4543752  1781818  4543752              4   36    1
4     4543753  1781819  4543753              1   41    1
[0 0 0 0 0 0 0]
4543750
[4543749 4543750 4543751 4543752]
   Unnamed: 0      hid      pid  person_number  age  sex
0     4543749  1781818  4543749              1   37    2
1     4543750  1781818  4543750              2    7    1
2     4543751  1781818  4543751              3    5    2
3     4543752  1781818  4543752              4   36    1
4     4543753  1781819  4543753              1   41    1
[0 0 0 0 0 0 0]
4543751
[4543749 4543750 4543751 4543752]
   Unnamed: 0      hid      pid  person_number  age  sex
0     4543749  1781818  4543749              1   37    2
1     4543750  1781818  4543750             

In [ ]:
from preprocess import PreProcessor

p = PreProcessor(va_activity_loc_assign, va_activity_locations, va_disease_outcome_target, va_disease_outcome_training, va_household, va_person, va_population_network, va_residence_locations)
p.get_training_labels(4543889)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])